site_name:        SAIGtensor.jl
repo_url:         https://github.com/WneleiGao/SAIGtensor.jl
site_description: Tensor tools for seismic data processing
site_author:      Wenlei Gao

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
